# html lang
language: zh-Hans

# main menu navigation
menu:
  home: /
  post:
    categories: /categories
    archives: /archives
    tags: /tags

  Papers: /paper
  project: /project
  activity: /activity
  search: /search
  about: /about
  # rss: /atom.xml

# Miscelaneous
favicon: footer-logo.png
logo:

share:
  show: false
  img:
  img_alt:
  tip_text: test

# stylesheets loaded in the <head>
stylesheets:
  # - /css/normalize.css
  - //cdn.bootcss.com/pure/1.0.0/pure-min.css
  - /css/xoxo.css

# baidu url js push
baidu_url_js_push: true

# comment extend, support gialk, giscus
# giscus https://giscus.app/zh-CN
comment_extend:
  gitalk:
    enable: false
    owner: Github username
    repo: issue repo name
    admin: github username
    clientID: xxx
    clientSecret: xxx
  giscus:
    enable: true
    repo: "dgjungleP/communicate"
    repoId: "R_kgDOJPoMuA"
    dataCategoryId: "DIC_kwDOJPoMuM4CVXdN"

# scripts loaded in the end of the body
scripts:
#- //cdn.bootcss.com/zepto/1.2.0/zepto.min.js
#- /js/xoxo.js

# switch
show_excerpt: true
show_date: true

#footer
index_page: https://dgjunglep.github.io/
main_site: https://dgjunglep.github.io/
github: https://github.com/dgjungleP
links_url: /links

# 友情链接
links:
  Fooying(主题作者): https://www.fooying.com
# project
projects:
  # hexo-theme-xoxo-plus:
  #   url: https://github.com/fooying/hexo-theme-xoxo-plus
  #   descript: a hexo theme

# activitys
activitys:
  100DaysCode:
    date: 2023-03-30
    # url: https://ke.qq.com/course/342390?tuin=49018ed
    type: 挑战
# papers
papers:
  # 原创翻译：给开发者的终极XSS防护备忘录: https://github.com/fooying/Papers/blob/master/给开发者的终极XSS防护备忘录.pdf
